### Packages

In [1]:
import pandas as pd

## 📌 축제공연행사
- 축제
- 공연행사

### 🔴 축제

In [3]:
fest_g = pd.read_excel('./data_info/축제공연행사/축제공연행사_축제_경기도.xls')
fest_s = pd.read_excel('./data_info/축제공연행사/축제공연행사_축제_서울.xls')
fest_i = pd.read_excel('./data_info/축제공연행사/축제공연행사_축제_인천.xls')

# '지역' 컬럼 추가 
fest_g['지역'] = '경기도'
fest_s['지역'] = '서울'
fest_i['지역'] = '인천'

# 각 데이터 columns 확인
print('축제_경기도 컬럼: ', fest_g.columns)
print('축제_서울 컬럼: ', fest_s.columns)
print('축제_인천 컬럼: ', fest_i.columns)

# 각 데이터 개수 확인
print('축제_경기도 데이터 갯수: ', fest_g['명칭'].count())
print('축제_서울 데이터 갯수: ', fest_s['명칭'].count())
print('축제_인천 데이터 갯수: ', fest_i['명칭'].count())

In [12]:
# 데이터 합치기
fest_df = pd.concat([fest_g, fest_s, fest_i])
# 오름차순 정렬
fest_df.sort_values(by='명칭', inplace=True)
#확인
display(fest_df.head())
display(fest_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 347 entries, 0 to 36
Data columns (total 29 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   명칭        347 non-null    object
 1   우편번호      341 non-null    float64
 2   관리자       346 non-null    object
 3   전화번호      339 non-null    object
 4   주소        347 non-null    object
 5   위도        347 non-null    float64
 6   경도        347 non-null    float64
 7   개요        345 non-null    object
 8   주최자 정보    346 non-null    object
 9   주최자 연락처   339 non-null    object
 10  주관사 정보    276 non-null    object
 11  주관사 연락처   128 non-null    object
 12  행사시작일     347 non-null    int64
 13  행사종료일     347 non-null    int64
 14  공연시간      322 non-null    object
 15  행사장소      342 non-null    object
 16  이벤트 홈페이지  1 non-null      object
 17  이용요금      337 non-null    object
 18  할인정보      0 non-null      float64
 19  관람소요시간    26 non-null     object
 20  관람가능연령    37 non-null     object
 21  예매처       0 non-null      float64
 22  행사장 위치안내  6 non-null      object
 23  부대행사      2 non-null      object
 24  프로그램      0 non-null      float64
 25  상세정보      347 non-null    object
 26  진행형태      316 non-null    object
 27  축제형태      315 non-null    object
 28  지역        347 non-null    object
dtypes: float64(6), int64(2), object(21)
memory usage: 81.3+ KB

In [17]:
# 내보내기
fest_df.to_excel('./data_info/중분류데이터/축제공연행사_축제.xlsx')

### 🔴 공연행사

In [18]:
concert_g = pd.read_excel('./data_info/축제공연행사/축제공연행사_공연행사_경기도.xls')
concert_s = pd.read_excel('./data_info/축제공연행사/축제공연행사_공연행사_서울.xls')
concert_i = pd.read_excel('./data_info/축제공연행사/축제공연행사_공연행사_인천.xls')

# '지역' 컬럼 추가 
concert_g['지역'] = '경기도'
concert_s['지역'] = '서울'
concert_i['지역'] = '인천'

# 각 데이터 columns 확인
print('공연행사_경기도 컬럼: ', concert_g.columns)
print('공연행사_서울 컬럼: ', concert_s.columns)
print('공연행사_인천 컬럼: ', concert_i.columns)

# 각 데이터 개수 확인
print('공연행사_경기도 데이터 갯수: ', concert_g['명칭'].count())
print('공연행사_서울 데이터 갯수: ', concert_s['명칭'].count())
print('공연행사_인천 데이터 갯수: ', concert_i['명칭'].count())

공연행사_경기도 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '주최자 정보',
       '주최자 연락처', '주관사 정보', '주관사 연락처', '행사시작일', '행사종료일', '공연시간', '행사장소',
       '이벤트 홈페이지', '이용요금', '할인정보', '관람소요시간', '관람가능연령', '예매처', '행사장 위치안내',
       '부대행사', '프로그램', '상세정보', '진행형태', '축제형태', '지역'],
      dtype='object')
공연행사_서울 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '주최자 정보',
       '주최자 연락처', '주관사 정보', '주관사 연락처', '행사시작일', '행사종료일', '공연시간', '행사장소',
       '이벤트 홈페이지', '이용요금', '할인정보', '관람소요시간', '관람가능연령', '예매처', '행사장 위치안내',
       '부대행사', '프로그램', '상세정보', '진행형태', '축제형태', '지역'],
      dtype='object')
공연행사_인천 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '주최자 정보',
       '주최자 연락처', '주관사 정보', '주관사 연락처', '행사시작일', '행사종료일', '공연시간', '행사장소',
       '이벤트 홈페이지', '이용요금', '할인정보', '관람소요시간', '관람가능연령', '예매처', '행사장 위치안내',
       '부대행사', '프로그램', '상세정보', '진행형태', '축제형태', '지역'],
      dtype='object')
공연행사_경기도 데이터 갯수:  61
공연행사_서울 데이터 갯수:  122
공연행사_인천 데이터 갯수:  9

In [19]:
# 데이터 합치기
concert_df = pd.concat([concert_g, concert_s, concert_i])
# 오름차순 정렬
concert_df.sort_values(by='명칭', inplace=True)
#확인
display(concert_df.head())
display(concert_df.info())

,명칭,우편번호,관리자,전화번호,주소,위도,경도,개요,주최자 정보,주최자 연락처,...,관람소요시간,관람가능연령,예매처,행사장 위치안내,부대행사,프로그램,상세정보,진행형태,축제형태,지역
55,2022 SAC FESTA 밤도깨비 상영회,6757.0,예술의전당,02-580-1300,서울특별시 서초구 남부순환로 2406 예술의전당,37.480484,127.013470,2022 SAC FESTA 밤도깨비 상영회<br>한 여름밤 무더위를 날려 줄 총 7...,예술의전당,02-580-1300,...,NaN,NaN,NaN,NaN,NaN,NaN,행사소개:2022 SAC FESTA 밤도깨비 상영회<br>한 여름밤 무더위를 날려 ...,선택안함,선택안함,서울
63,2022 국제저작권기술 콘퍼런스,3183.0,문화체육관광부,010-6246-6918,서울특별시 종로구 새문안로 97,37.570751,126.975413,"저작권 대중화를 위한 기술적 도전 이라는 주제로 열리는 이번 콘퍼런스는 AI, 웹소...",문화체육관광부,010-6246-6918,...,총 7시간 30분,전체연령,NaN,NaN,NaN,NaN,행사소개:저작권 대중화를 위한 기술적 도전 이라는 주제로 열리는 이번 콘퍼런스는 A...,선택안함,선택안함,서울
51,2022 국토발전전시관 문화행사,4516.0,국토발전전시관,010-3098-3722,서울특별시 중구 정동길 18 국토발전전시관,37.566862,126.970097,"어린이와 가족이 함께 즐길 수 있는 문화 행사 공연, 체험, 만화 상영을 무료로 즐...",국토발전전시관,010-3098-3722,...,NaN,NaN,NaN,NaN,NaN,NaN,"행사소개:어린이와 가족이 함께 즐길 수 있는 문화 행사 공연, 체험, 만화 상영을 ...",선택안함,선택안함,서울
48,2022 예술한류 콜로키엄 [상반기],2789.0,한국예술종합학교 전통예술원,010-3199-0220,서울특별시 성북구 화랑로32길 146-37 한국예술종합학교,37.605048,127.057985,"2022 예술한류 콜로키엄은 전통예술 선도사업의 체계화를 위해 상반기 2회, 하반기...",한국예술종합학교 전통예술원,010-3199-0220,...,NaN,NaN,NaN,NaN,NaN,NaN,행사소개:2022 예술한류 콜로키엄은 전통예술 선도사업의 체계화를 위해 상반기 2회...,선택안함,선택안함,서울
49,2022년 북촌 한옥 역사관 상반기 특별행사,3057.0,서울특별시,02-737-6444,서울특별시 종로구 계동4길 3,37.582358,126.987078,[북촌 툇마루 기행]은 북촌 한옥역사관에 방문하는 시민을 대상으로 툇마루에 앉아 편...,서울특별시,02-737-6444,...,NaN,NaN,NaN,NaN,NaN,NaN,행사소개:[북촌 툇마루 기행]은 북촌 한옥역사관에 방문하는 시민을 대상으로 툇마루에...,선택안함,선택안함,서울

<class 'pandas.core.frame.DataFrame'>
Index: 192 entries, 55 to 21
Data columns (total 29 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   명칭        192 non-null    object
 1   우편번호      190 non-null    float64
 2   관리자       192 non-null    object
 3   전화번호      189 non-null    object
 4   주소        191 non-null    object
 5   위도        192 non-null    float64
 6   경도        192 non-null    float64
 7   개요        192 non-null    object
 8   주최자 정보    192 non-null    object
 9   주최자 연락처   189 non-null    object
 10  주관사 정보    149 non-null    object
 11  주관사 연락처   91 non-null     object
 12  행사시작일     192 non-null    int64
 13  행사종료일     192 non-null    int64
 14  공연시간      177 non-null    object
 15  행사장소      189 non-null    object
 16  이벤트 홈페이지  3 non-null      object
 17  이용요금      186 non-null    object
 18  할인정보      3 non-null      object
 19  관람소요시간    59 non-null     object
 20  관람가능연령    75 non-null     object
 21  예매처       5 non-null      object
 22  행사장 위치안내  5 non-null      object
 23  부대행사      1 non-null      object
 24  프로그램      0 non-null      float64
 25  상세정보      192 non-null    object
 26  진행형태      190 non-null    object
 27  축제형태      188 non-null    object
 28  지역        192 non-null    object
dtypes: float64(4), int64(2), object(23)
memory usage: 45.0+ KB

None

In [20]:
# 내보내기
fest_df.to_excel('./data_info/중분류데이터/축제공연행사_공연행사.xlsx')

## 📌 자연
- 관광자원
- 자연관광지

### 🔴 관광자원

In [21]:
nature1_g = pd.read_excel('./data_info/자연/자연_관광자원_경기도.xls')
nature1_s = pd.read_excel('./data_info/자연/자연_관광자원_서울.xls')
nature1_i = pd.read_excel('./data_info/자연/자연_관광자원_인천.xls')

# '지역' 컬럼 추가 
nature1_g['지역'] = '경기도'
nature1_s['지역'] = '서울'
nature1_i['지역'] = '인천'

# 각 데이터 columns 확인
print('관광자원_경기도 컬럼: ', nature1_g.columns)
print('관광자원_서울 컬럼: ', nature1_s.columns)
print('관광자원_인천 컬럼: ', nature1_i.columns)

# 각 데이터 개수 확인
print('관광자원_경기도 데이터 갯수: ', nature1_g['명칭'].count())
print('관광자원_서울 데이터 갯수: ', nature1_s['명칭'].count())
print('관광자원_인천 데이터 갯수: ', nature1_i['명칭'].count())

관광자원_경기도 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
관광자원_서울 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
관광자원_인천 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
관광자원_경기도 데이터 갯수:  5
관광자원_서울 데이터 갯수:  5
관광자원_인천 데이터 갯수:  5

In [23]:
# 데이터 합치기
nature1_df = pd.concat([nature1_g, nature1_s, nature1_i])
# 오름차순 정렬
nature1_df.sort_values(by='명칭', inplace=True)
# 확인
display(nature1_df.head())
display(nature1_df.info())

,명칭,우편번호,관리자,전화번호,주소,위도,경도,개요,유산구분,문의 및 안내,...,체험가능연령,수용인원,이용시기,이용시간,주차시설,유모차 대여 여부,애완동물 동반 가능 여부,신용카드 가능 여부,상세정보,지역
0,150년 수령 느티나무,NaN,NaN,NaN,서울 양천구 목4동 760-28,37.537686,126.868793,수령 150년 된 느티나무 고목으로 이 느티나무는 이곳이 대규모 주택단지로 변모하기...,NaN,02-2620-3407,...,NaN,NaN,NaN,NaN,NaN,없음,없음,NaN,NaN,서울
0,강화 갑곶리 탱자나무,23022.0,NaN,NaN,인천광역시 강화군 강화읍 동문로 119(강화읍),37.754146,126.494854,갑곶리에 있는 탱자나무는 사기리에 있는 탱자나무와 함께 천연기념물로 보호되고 있는 ...,NaN,032-930-3124,...,NaN,NaN,NaN,NaN,NaN,없음,없음,NaN,NaN,인천
1,강화 사기리 탱자나무,23059.0,강화군청,NaN,인천광역시 강화군 화도면 해안남로1114번길 6,37.616503,126.456723,"이건창 생가 맞은편에 위치한 사기리 탱자나무는 높이 4m, 밑 둘레 1m로, 땅 위...",NaN,032-930-3892,...,NaN,NaN,NaN,NaN,있음,없음,없음,NaN,NaN,인천
0,곤지바위,12804.0,NaN,NaN,경기도 광주시 곤지암로 72,37.349594,127.338761,곤지암 바위는 경기도 광주시 곤지암읍 곤지암로 72에 있다. 옛날에는 고양이 모양으...,NaN,031-760-4822,...,NaN,NaN,NaN,상시,없음,NaN,NaN,NaN,NaN,경기도
1,서울 신림동 굴참나무,8858.0,서울시 관악구,NaN,서울특별시 관악구 난곡로35길 28-7,37.471020,126.916974,서울 신림동 굴참나무는 남부순환로 난곡사거리에서 약 1.5km 정도 거리에 위치한 ...,NaN,관악구청 문화체육과 02-879-5618,...,NaN,NaN,NaN,NaN,NaN,없음,없음,NaN,NaN,서울

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 0 to 4
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   명칭             15 non-null     object
 1   우편번호           14 non-null     float64
 2   관리자            2 non-null      object
 3   전화번호           0 non-null      float64
 4   주소             15 non-null     object
 5   위도             15 non-null     float64
 6   경도             15 non-null     float64
 7   개요             15 non-null     object
 8    유산구분          0 non-null      float64
 9   문의 및 안내        15 non-null     object
 10  개장일            0 non-null      float64
 11  쉬는날            10 non-null     object
 12  체험안내           2 non-null      object
 13  체험가능연령         2 non-null      object
 14  수용인원           0 non-null      float64
 15  이용시기           0 non-null      float64
 16  이용시간           6 non-null      object
 17  주차시설           8 non-null      object
 18  유모차 대여 여부      13 non-null     object
 19  애완동물 동반 가능 여부  13 non-null     object
 20  신용카드 가능 여부     0 non-null      float64
 21  상세정보           7 non-null      object
 22  지역             15 non-null     object
dtypes: float64(9), object(14)
memory usage: 2.8+ KB

None

In [24]:
# 내보내기
nature1_df.to_excel('./data_info/중분류데이터/자연_관광자원.xlsx')

### 🔴 자연관광지

In [26]:
nature2_g = pd.read_excel('./data_info/자연/자연_자연관광지_경기도.xlsx')
nature2_s = pd.read_excel('./data_info/자연/자연_자연관광지_서울.xls')
nature2_i = pd.read_excel('./data_info/자연/자연_자연관광지_인천.xls')

# '지역' 컬럼 추가 
nature2_g['지역'] = '경기도'
nature2_s['지역'] = '서울'
nature2_i['지역'] = '인천'

# 각 데이터 columns 확인
print('자연관광지_경기도 컬럼: ', nature2_g.columns)
print('자연관광지_서울 컬럼: ', nature2_s.columns)
print('자연관광지_인천 컬럼: ', nature2_i.columns)

# 각 데이터 개수 확인
print('자연관광지_경기도 데이터 갯수: ', nature2_g['명칭'].count())
print('자연관광지_서울 데이터 갯수: ', nature2_s['명칭'].count())
print('자연관광지_인천 데이터 갯수: ', nature2_i['명칭'].count())

자연관광지_경기도 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
자연관광지_서울 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
자연관광지_인천 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
자연관광지_경기도 데이터 갯수:  316
자연관광지_서울 데이터 갯수:  61
자연관광지_인천 데이터 갯수:  115

In [27]:
# 데이터 합치기
nature2_df = pd.concat([nature2_g, nature2_s, nature2_i])
# 오름차순 정렬
nature2_df.sort_values(by='명칭', inplace=True)
# 확인
display(nature2_df.head())
display(nature2_df.info())

,명칭,우편번호,관리자,전화번호,주소,위도,경도,개요,유산구분,문의 및 안내,...,체험가능연령,수용인원,이용시기,이용시간,주차시설,유모차 대여 여부,애완동물 동반 가능 여부,신용카드 가능 여부,상세정보,지역
0,SK인천석유화학벚꽃동산,22771.0,NaN,NaN,인천광역시 서구 봉수대로 415(원창동),37.513308,126.660749,인천 서구 원창동 SK 석유화학단지 주변에 벚꽃 600여 그루를 심어 조성한 공원이...,NaN,032-570-5151,...,제한없음,NaN,NaN,10:00~15:00,있음,없음,불가,NaN,"입 장 료:없음\t\t\n\n화장실:있음(남,녀 구분)\n\n이용가능시설:벚꽃동산,...",인천
0,가덕산,"477-840,1",가평군청,NaN,경기 가평군 북면,37.920232,127.568310,"경기 제1봉인 화악산(1,468m)에서 동남쪽으로 뻗어 내린 능선상에 솟아있는 가덕...",NaN,031-582-8830 (가평 관광안내소),...,NaN,NaN,NaN,NaN,NaN,없음,없음,NaN,등산로:* 큰멱골 - 멱골수양관 - 앵상골 - 정상 (3시간 30분)<br />\n...,경기도
1,가리산(포천),11111,포천시청,NaN,경기도 포천시 이동면 장암리,38.043301,127.402805,백운산과 국망봉 사이에 위치한 신로봉에서 서쪽인 이동면 장암리 방면으로 뻗어 내린 ...,NaN,031-538-3342(산림경영팀),...,NaN,NaN,NaN,NaN,NaN,없음,없음,NaN,등산로:1코스(11km):이동면사무소>장암저수지>갈림길>능선안부>능선갈림길>정상>능...,경기도
2,갈산공원,12562,NaN,NaN,경기도 양평군 양평읍 양평체육공원길 24,37.483687,127.497326,갈산은 칡이 많다고 하여 붙은 양평읍의 옛 이름이다. 남한강변에 위치한 양평 생활 ...,NaN,031-770-3016,...,NaN,NaN,NaN,NaN,주차가능,없음,가능,NaN,"촬영장소:나혼자산다 380회 박은석편 촬영지\n\n이용가능시설:산책로, 자전거길, ...",경기도
3,감악산(파주),10805,NaN,NaN,경기도 파주시 적성면 감골길 48,37.912144,126.952064,"감악산은 파주시, 양주시, 연천군 사이에 있는 높이 675m의 산이다. 예부터 바위...",NaN,031-950-1902(감악산관리사무소) / 031-940-8516(관광과),...,전연령,NaN,NaN,상시개방(기상여건에 따라 입산금지 가능함),있음(제1~제5주차장),불가,불가,NaN,"입 장 료:무료\n주차요금:소형(승차정원 35인 이하) 2,000원 / 대형:4,0...",경기도

<class 'pandas.core.frame.DataFrame'>
Index: 492 entries, 0 to 114
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   명칭             492 non-null    object
 1   우편번호           453 non-null    object
 2   관리자            34 non-null     object
 3   전화번호           18 non-null     object
 4   주소             492 non-null    object
 5   위도             492 non-null    float64
 6   경도             492 non-null    float64
 7   개요             492 non-null    object
 8    유산구분          1 non-null      object
 9   문의 및 안내        471 non-null    object
 10  개장일            58 non-null     object
 11  쉬는날            271 non-null    object
 12  체험안내           140 non-null    object
 13  체험가능연령         61 non-null     object
 14  수용인원           22 non-null     object
 15  이용시기           7 non-null      object
 16  이용시간           283 non-null    object
 17  주차시설           365 non-null    object
 18  유모차 대여 여부      435 non-null    object
 19  애완동물 동반 가능 여부  443 non-null    object
 20  신용카드 가능 여부     0 non-null      float64
 21  상세정보           402 non-null    object
 22  지역             492 non-null    object
dtypes: float64(3), object(20)
memory usage: 92.2+ KB

None

In [28]:
# 내보내기
nature2_df.to_excel('./data_info/중분류데이터/자연_자연관광지.xlsx')

## 📌 인문
- 역사관광지
- 휴양관광지

### 🔴 역사관광지

In [29]:
hist_g = pd.read_excel('./data_info/인문/인문_역사관광지_경기도.xlsx')
hist_s = pd.read_excel('./data_info/인문/인문_역사관광지_서울.xlsx')
hist_i = pd.read_excel('./data_info/인문/인문_역사관광지_인천.xls')

# '지역' 컬럼 추가 
hist_g['지역'] = '경기도'
hist_s['지역'] = '서울'
hist_i['지역'] = '인천'

# 각 데이터 columns 확인
print('역사관광지_경기도 컬럼: ', hist_g.columns)
print('역사관광지_서울 컬럼: ', hist_s.columns)
print('역사관광지_인천 컬럼: ', hist_i.columns)

# 각 데이터 개수 확인
print('역사관광지_경기도 데이터 갯수: ', hist_g['명칭'].count())
print('역사관광지_서울 데이터 갯수: ', hist_s['명칭'].count())
print('역사관광지_인천 데이터 갯수: ', hist_i['명칭'].count())

역사관광지_경기도 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
역사관광지_서울 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
역사관광지_인천 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
역사관광지_경기도 데이터 갯수:  308
역사관광지_서울 데이터 갯수:  202
역사관광지_인천 데이터 갯수:  80

In [30]:
# 데이터 합치기
hist_df = pd.concat([hist_g, hist_s, hist_i])
# 오름차순 정렬
hist_df.sort_values(by='명칭', inplace=True)
# 확인
display(hist_df.head())
display(hist_df.info())

,명칭,우편번호,관리자,전화번호,주소,위도,경도,개요,유산구분,문의 및 안내,...,체험가능연령,수용인원,이용시기,이용시간,주차시설,유모차 대여 여부,애완동물 동반 가능 여부,신용카드 가능 여부,상세정보,지역
0,(구)인천일본제58은행지점,22314,NaN,NaN,인천광역시 중구 신포로23번길 69-1 중구음식업지부,37.472867,126.621384,일본 오사카에 본점을 둔 일본 제58은행의 인천지점으로 1892년에 개점하였다. 1...,NaN,032-760-6474,...,NaN,NaN,NaN,09:00~18:00,없음,없음,불가,NaN,외국어 안내서비스:영문 / 일어 / 중국어 팸플릿 비치\n,인천
0,1.21 무장공비 침투로,"486-890,1",NaN,NaN,경기도 연천군 장남면 반정리 294,37.970202,126.828157,※ 민통초소에 신분증 제시하여 출입 가능 (25인 이상 출입시 일주일 전 신청서 제...,NaN,031-839-2061,...,NaN,NaN,NaN,[출입가능시간] 10:00~16:00(12:00~13:00 제외),NaN,없음,불가,NaN,화장실:있음\n,경기도
1,38선마을,11049,NaN,NaN,경기도 연천군 백학면 노곡로42번길 5,37.995289,126.923608,38선마을은 연천군 서남쪽에 위치하여 9km 전방에 휴전선과 마을 입구에 임진강이 ...,NaN,031-835-1124,...,NaN,NaN,NaN,상시이용가능,NaN,없음,없음,NaN,NaN,경기도
2,DMZ 생생누리,10808,NaN,NaN,경기도 파주시 임진각로 148-53 종합관광안내소,37.890501,126.740403,DMZ 생생누리는 DMZ를 보다 가깝고 생생하게 체험하고 즐길 수 있는 곳이라는 뜻...,NaN,070-4123-1393,...,NaN,NaN,NaN,이용시간 : 10:00~18:00(입장 마감 17:00)<br>관람소요시간 : 약 1시간,NaN,NaN,NaN,NaN,"입 장 료:성인 8,000원 / 청소년 및 어린이 할인 적용 등\n주차요금:소형 2...",경기도
3,가월리 · 주월리 구석기 유적,10802,NaN,NaN,경기도 파주시 적성면 달빛길 345,37.984193,126.904230,가월리·주월리 구석기유적(佳月里·舟月里 舊石器遺跡)는 임진강 하안단구 일대에 형성된...,NaN,031-940-5831<br />\n031-940-4354,...,NaN,NaN,NaN,상시이용가능,NaN,없음,없음,NaN,NaN,경기도

<class 'pandas.core.frame.DataFrame'>
Index: 590 entries, 0 to 201
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   명칭             590 non-null    object
 1   우편번호           583 non-null    object
 2   관리자            2 non-null      object
 3   전화번호           2 non-null      object
 4   주소             590 non-null    object
 5   위도             590 non-null    float64
 6   경도             590 non-null    float64
 7   개요             590 non-null    object
 8    유산구분          18 non-null     object
 9   문의 및 안내        588 non-null    object
 10  개장일            26 non-null     object
 11  쉬는날            339 non-null    object
 12  체험안내           105 non-null    object
 13  체험가능연령         48 non-null     object
 14  수용인원           13 non-null     object
 15  이용시기           2 non-null      object
 16  이용시간           300 non-null    object
 17  주차시설           410 non-null    object
 18  유모차 대여 여부      573 non-null    object
 19  애완동물 동반 가능 여부  573 non-null    object
 20  신용카드 가능 여부     0 non-null      float64
 21  상세정보           422 non-null    object
 22  지역             590 non-null    object
dtypes: float64(3), object(20)
memory usage: 110.6+ KB

None

In [31]:
# 내보내기
hist_df.to_excel('./data_info/중분류데이터/인문_역사관광지.xlsx')

### 🔴 휴양관광지

In [32]:
resort_g1 = pd.read_excel('./data_info/인문/인문_휴양관광지_경기도1.xls')
resort_g2 = pd.read_excel('./data_info/인문/인문_휴양관광지_경기도2.xls')
resort_s = pd.read_excel('./data_info/인문/인문_휴양관광지_서울.xls')
resort_i = pd.read_excel('./data_info/인문/인문_휴양관광지_인천.xls')

# '지역' 컬럼 추가 
resort_g1['지역'] = '경기도'
resort_g2['지역'] = '경기도'
resort_s['지역'] = '서울'
resort_i['지역'] = '인천'

# 각 데이터 columns 확인
print('휴양관광지_경기도1 컬럼: ', resort_g1.columns)
print('휴양관광지_경기도2 컬럼: ', resort_g2.columns)
print('휴양관광지_서울 컬럼: ', resort_s.columns)
print('휴양관광지_인천 컬럼: ', resort_i.columns)

# 각 데이터 개수 확인
print('휴양관광지_경기도1 데이터 갯수: ', resort_g1['명칭'].count())
print('휴양관광지_경기도2 데이터 갯수: ', resort_g2['명칭'].count())
print('휴양관광지_서울 데이터 갯수: ', resort_s['명칭'].count())
print('휴양관광지_인천 데이터 갯수: ', resort_i['명칭'].count())

휴양관광지_경기도1 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
휴양관광지_경기도2 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
휴양관광지_서울 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
휴양관광지_인천 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', ' 유산구분', '문의 및 안내',
       '개장일', '쉬는날', '체험안내', '체험가능연령', '수용인원', '이용시기', '이용시간', '주차시설',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보', '지역'],
      dtype='object')
휴양관광지_경기도1 데이터 갯수:  200
휴양관광지_경기도2 데이터 갯수:  200
휴양관광지_서울 데이터 갯수:  200
휴양관광지_인천 데이터 갯수:  95

In [33]:
# 데이터 합치기
resort_df = pd.concat([resort_g1, resort_g2, resort_s, resort_i])
# 오름차순 정렬
resort_df.sort_values(by='명칭', inplace=True)
# 확인
display(resort_df.head())
display(resort_df.info())

,명칭,우편번호,관리자,전화번호,주소,위도,경도,개요,유산구분,문의 및 안내,...,체험가능연령,수용인원,이용시기,이용시간,주차시설,유모차 대여 여부,애완동물 동반 가능 여부,신용카드 가능 여부,상세정보,지역
81,AHC스파,6026.0,NaN,NaN,서울특별시 강남구 도산대로 237(신사동),37.521772,127.033028,한국의 K뷰티를 알리고 있는 AHC 코스메틱으로만 케어해 드리고 있는 AHC스파입니...,NaN,02-541-8239,...,NaN,NaN,NaN,12:00~21:00,NaN,없음,없음,NaN,외국인 예약안내:전화/홈페이지 예약 가능\n내국인 예약안내:전화/홈페이지 예약 가능\n,서울
89,SPA 1899 동인비,6176.0,NaN,NaN,서울특별시 강남구 영동대로 416(대치동),37.506638,127.065343,한방에서는 조금만 움직여도 땀이 나고 더운 여름에는 원기 소모가 심하다고 말한다. ...,NaN,02-557-8030,...,NaN,NaN,NaN,10:00 ~ 22:00,NaN,없음,없음,NaN,NaN,서울
33,가나아트파크,11520.0,NaN,NaN,경기도 양주시 장흥면 권율로 117,37.725452,126.949750,장흥관광지의 두리랜드 맞은편에 있는 가나아트파크는 작가들의 창작공간인 아틀리에와 체...,NaN,031-877-0500,...,프로그램에 따라 다름,NaN,NaN,[평일] <br>\n- 10:00~18:00(입장마감 17:00) <br>\n[주말...,"있음 <br> ※ 단, 가나아트파크 운영시간 중에만 운영",없음,불가,NaN,이용가능시설:가나 어린이미술관 / 블루 스페이스(피카소어린이미술관) / 레드 스페이...,경기도
138,가남체육공원,12662.0,NaN,NaN,경기도 여주시 가남읍 대명산길 98,37.201709,127.534914,가남체육공원은 가남면 태평리에 위치한 주민들을 위한 다목적 체육활동 공원이다. 20...,NaN,031-887-3832,...,NaN,NaN,NaN,00:00 ~ 24:00,주차가능,없음,없음,NaN,입 장 료:없음(체육시설 이용료 별도)\t\t\n\n이용가능시설:족구장 2면/ 축구...,경기도
18,가막들공원,16007.0,NaN,NaN,경기도 의왕시 양지편로 41-2(청계동),37.391692,126.995697,가막들 공원은 경기도 의왕시 청계동에 위치한 공원이다. 어린이 놀이터는 물론 어린이...,NaN,031-345-3833,...,NaN,NaN,NaN,상시 개장,주차가능,없음,없음,NaN,"화장실:가능\n이용가능시설:하우놀이터(어린이 놀이터), 집라인\n",경기도

<class 'pandas.core.frame.DataFrame'>
Index: 695 entries, 81 to 108
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   명칭             695 non-null    object
 1   우편번호           668 non-null    float64
 2   관리자            5 non-null      object
 3   전화번호           3 non-null      object
 4   주소             695 non-null    object
 5   위도             695 non-null    float64
 6   경도             695 non-null    float64
 7   개요             693 non-null    object
 8    유산구분          0 non-null      float64
 9   문의 및 안내        671 non-null    object
 10  개장일            117 non-null    object
 11  쉬는날            455 non-null    object
 12  체험안내           156 non-null    object
 13  체험가능연령         66 non-null     object
 14  수용인원           43 non-null     object
 15  이용시기           3 non-null      object
 16  이용시간           529 non-null    object
 17  주차시설           586 non-null    object
 18  유모차 대여 여부      566 non-null    object
 19  애완동물 동반 가능 여부  588 non-null    object
 20  신용카드 가능 여부     0 non-null      float64
 21  상세정보           646 non-null    object
 22  지역             695 non-null    object
dtypes: float64(5), object(18)
memory usage: 130.3+ KB

None

In [34]:
# 내보내기
resort_df.to_excel('./data_info/중분류데이터/인문_휴양관광지.xlsx')

## 📌 문화시설
- 공연장
- 기념관
- 대형서점
- 문화전수시설
- 미술관화랑
- 박물관
- 외국문화원
- 전시관

In [42]:
concert_g = pd.read_excel('./data_info/문화시설/문화시설_공연장_경기도.xls')
concert_s = pd.read_excel('./data_info/문화시설/문화시설_공연장_서울.xls')
concert_i = pd.read_excel('./data_info/문화시설/문화시설_공연장_인천.xls')

memorial_g = pd.read_excel('./data_info/문화시설/문화시설_기념관_경기도.xls')
memorial_s = pd.read_excel('./data_info/문화시설/문화시설_기념관_서울.xls')
memorial_i = pd.read_excel('./data_info/문화시설/문화시설_기념관_인천.xls')

book_g = pd.read_excel('./data_info/문화시설/문화시설_대형서점_경기도.xls')
book_s = pd.read_excel('./data_info/문화시설/문화시설_대형서점_서울.xls')

culture_g = pd.read_excel('./data_info/문화시설/문화시설_문화전수시설_경기도.xls')
culture_s = pd.read_excel('./data_info/문화시설/문화시설_문화전수시설_서울.xls')
culture_i = pd.read_excel('./data_info/문화시설/문화시설_문화전수시설_인천.xls')

art_g = pd.read_excel('./data_info/문화시설/문화시설_미술관화랑_경기도.xls')
art_s = pd.read_excel('./data_info/문화시설/문화시설_미술관화랑_서울.xls')
art_i = pd.read_excel('./data_info/문화시설/문화시설_미술관화랑_인천.xls')

museum_g = pd.read_excel('./data_info/문화시설/문화시설_박물관_경기도.xls')
museum_s = pd.read_excel('./data_info/문화시설/문화시설_박물관_서울.xls')
museum_i = pd.read_excel('./data_info/문화시설/문화시설_박물관_인천.xls')

fculture_g = pd.read_excel('./data_info/문화시설/문화시설_외국문화원_경기도.xls')
fculture_s = pd.read_excel('./data_info/문화시설/문화시설_외국문화원_서울.xls')

display_g = pd.read_excel('./data_info/문화시설/문화시설_전시관_경기도.xls')
display_s = pd.read_excel('./data_info/문화시설/문화시설_전시관_서울.xls')
display_i = pd.read_excel('./data_info/문화시설/문화시설_전시관_인천.xls')



# 각 데이터 columns 확인
print('공연장 컬럼: ', concert_g.columns)
print('기념관 컬럼: ', memorial_g.columns)
print('대형서점 컬럼: ', book_g.columns)
print('문화전수시설 컬럼: ', culture_g.columns)
print('미술관화랑 컬럼: ', art_g.columns)
print('박물관 컬럼: ', museum_g.columns)
print('외국문화원 컬럼: ', fculture_g.columns)
print('전시관 컬럼: ', display_g.columns)

공연장 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '이용시간', '쉬는날', '이용요금', '할인정보', '관람소요시간', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
기념관 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '이용시간', '쉬는날', '이용요금', '할인정보', '관람소요시간', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
대형서점 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '이용시간', '쉬는날', '이용요금', '할인정보', '관람소요시간', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
문화전수시설 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '이용시간', '쉬는날', '이용요금', '할인정보', '관람소요시간', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
미술관화랑 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '이용시간', '쉬는날', '이용요금', '할인정보', '관람소요시간', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
박물관 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '이용시간', '쉬는날', '이용요금', '할인정보', '관람소요시간', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
외국문화원 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '이용시간', '쉬는날', '이용요금', '할인정보', '관람소요시간', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
전시관 컬럼:  Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '이용시간', '쉬는날', '이용요금', '할인정보', '관람소요시간', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')

In [43]:
# '지역' 컬럼 추가 
concert_g['지역'] = '경기도'
concert_s['지역'] = '서울'
concert_i['지역'] = '인천'

memorial_g['지역'] = '경기도'
memorial_s['지역'] = '서울'
memorial_i['지역'] = '인천'

book_g['지역'] = '경기도'
book_s['지역'] = '서울'

culture_g['지역'] = '경기도'
culture_s['지역'] = '서울'
culture_i['지역'] = '인천'

art_g['지역'] = '경기도'
art_s['지역'] = '서울'
art_i['지역'] = '인천'

museum_g['지역'] = '경기도'
museum_s['지역'] = '서울'
museum_i['지역'] = '인천'

fculture_g['지역'] = '경기도'
fculture_s['지역'] = '서울'

display_g['지역'] = '경기도'
display_s['지역'] = '서울'
display_i['지역'] = '인천'




# 데이터 합치기
cultural_df = pd.concat([concert_g, concert_s, concert_i, memorial_g, memorial_s, memorial_i, book_g, book_s,
                        culture_g, culture_s, culture_i, art_g, art_s, art_i, museum_g, museum_s,
                        museum_i, fculture_g, fculture_s, display_g, display_s, display_i])
# 오름차순 정렬
resort_df.sort_values(by='명칭', inplace=True)

In [44]:
# 확인
display(cultural_df.head())
display(cultural_df.info())

,명칭,우편번호,관리자,전화번호,주소,위도,경도,개요,문의 및 안내,규모,...,이용요금,할인정보,관람소요시간,주차시설,주차요금,유모차 대여 여부,애완동물 동반 가능 여부,신용카드 가능 여부,상세정보,지역
0,수원야외음악당,16491.0,NaN,NaN,경기도 수원시 팔달구 동수원로 335(인계동),37.259299,127.036397,"수원 야외음악당은 삼성전자에서 건립, 수원시에 기증한 최신 첨단 음향 장비를 갖춘 ...",NaN,"대지면적 23,164㎡",...,공연에 따라 상이,NaN,NaN,가능(민방위 주차장 / 현충탑 주차장)<br>요금(민방위 주차장 : 무료 / 현충탑...,NaN,없음,불가,없음,"사업내용:각종문화예술(음악, 연극, 영화, 뮤지컬, 대중음악)공연\n대관안내:공연장...",경기도
1,수원시민회관,16444.0,NaN,NaN,경기도 수원시 팔달구 팔달산로 28 수원문화원,37.273650,127.011332,"수원시민회관은 1962년 4월 시민관이라는 이름으로 건립되었으며, 수원시민들의 문화...",NaN,"대지면적 : 7,826㎡ (2,371평) <br>\n건물면적 : 3,147㎡ (95...",...,공연에 따라 상이,NaN,공연에 따라 상이,가능,NaN,없음,불가,없음,대관안내:대관 가능(사전예약 필수)\n,경기도
2,가평문화예술회관,12416.0,NaN,NaN,경기도 가평군 가평읍 문화로 131,37.824248,127.508526,가평 문화 예술 회관은 가평군의 유일한 극장으로서 지역주민의 문화적 욕구를 충족시키...,NaN,"부지면적 : 5135㎡, 건축연면적 : 4801㎡(지상2, 지하2층)<br>\n전시...",...,공연 및 전시별 상이,NaN,NaN,가능<br>요금(무료),NaN,없음,불가,가능,"사업내용:문화예술행사, 영화상영, 연극공연\n대관안내:대관시설 : 공연장, 다목적실...",경기도
3,고양시문예회관,10460.0,NaN,NaN,경기도 고양시 덕양구 고양시청로 10(주교동),37.658383,126.831960,"고양시 문예회관은 고양 시청 및 고양시 의회와 같은 곳에 위치해 있으며, 1989년...",NaN,"총 부지면적 13,515㎡ (4,988평)<br />\n연면적 4,922㎡ (1,4...",...,"[대관료] -평일 70,000~200,000원 / 휴일 80,000~250,000원",NaN,NaN,"가능<br>요금(최초 1시간 무료 / 이후 30분당 1,000원)",NaN,없음,불가,없음,대관안내:고양문화재단 홈페이지를 통해 신청\n,경기도
4,부천시민회관,14613.0,NaN,NaN,경기도 부천시 부일로 365,37.488185,126.770448,부천시민운동장 옆에 자리한 부천시민회관은 1988년 개관하여 문화예술 공간으로 시민...,NaN,"지상 3층, 지하 2층<br> 면적 10,417㎡",...,공연에 따라 상이,NaN,NaN,가능,NaN,없음,불가,없음,"사업내용:대관 및 기획공연\n대관안내:[대관시설] 대공연장, 소공연장 (문의 : 0...",경기도

<class 'pandas.core.frame.DataFrame'>
Index: 737 entries, 0 to 23
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   명칭             737 non-null    object
 1   우편번호           735 non-null    float64
 2   관리자            5 non-null      object
 3   전화번호           12 non-null     object
 4   주소             736 non-null    object
 5   위도             737 non-null    float64
 6   경도             737 non-null    float64
 7   개요             736 non-null    object
 8   문의 및 안내        0 non-null      float64
 9   규모             323 non-null    object
 10  수용인원           238 non-null    object
 11  이용시간           725 non-null    object
 12  쉬는날            676 non-null    object
 13  이용요금           644 non-null    object
 14  할인정보           112 non-null    object
 15  관람소요시간         241 non-null    object
 16  주차시설           662 non-null    object
 17  주차요금           288 non-null    object
 18  유모차 대여 여부      604 non-null    object
 19  애완동물 동반 가능 여부  618 non-null    object
 20  신용카드 가능 여부     626 non-null    object
 21  상세정보           607 non-null    object
 22  지역             737 non-null    object
dtypes: float64(4), object(19)
memory usage: 138.2+ KB

None

In [45]:
# 내보내기
cultural_df.to_excel('./data_info/중분류데이터/문화시설.xlsx')

## 📌 레포츠
- 레포츠소개
- 복합레포츠
- 수상레포츠
- 육상레포츠
    - ATV
    - MTB
    - 경마
    - 번지점프
    - 스케이트
    - 스키,스노보드
    - 승마
    - 썰매장
    - 야영장,오토캠핑장
    - 암벽등반
    - 인라인
    - 자전거하이킹
    - 카지노
    - 카트
    - 트래킹
- 항공레포츠

In [47]:
so_g = pd.read_excel('./data_info/레포츠/레포츠_레포츠소개_경기도.xls')
so_s = pd.read_excel('./data_info/레포츠/레포츠_레포츠소개_서울.xls')

complx_g = pd.read_excel('./data_info/레포츠/레포츠_복합레포츠_경기도.xls')
complx_s = pd.read_excel('./data_info/레포츠/레포츠_복합레포츠_서울.xls')
complx_i = pd.read_excel('./data_info/레포츠/레포츠_복합레포츠_인천.xls')

water_g = pd.read_excel('./data_info/레포츠/레포츠_수상레포츠_경기도.xls')
water_s = pd.read_excel('./data_info/레포츠/레포츠_수상레포츠_서울.xls')
water_i = pd.read_excel('./data_info/레포츠/레포츠_수상레포츠_인천.xls')

r_atv_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_ATV_경기도.xls')

r_mtb_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_MTB_서울.xls')

r_ghorse_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_경마_경기도.xls')

r_jump_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_번지점프_경기도.xls')

r_skate_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_스케이트_경기도.xls')
r_skate_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_스케이트_서울.xls')
r_skate_i = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_스케이트_인천.xls')

r_ski_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_스키,스노보드_경기도.xls')

r_shorse_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_승마_경기도.xls')
r_shorse_i = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_승마_인천.xls')

r_snowride_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_썰매장_경기도.xls')
r_snowride_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_썰매장_서울.xls')
r_snowride_i = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_썰매장_인천.xls')

r_camping_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_야영, 오토캠핑장_경기도.xls')
r_camping_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_아영장,오토캠핑장_서울.xls')
r_camping_i = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_야영, 오토캠핑장_인천.xls')

r_climb_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_암벽등반_경기도.xls')
r_climb_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_암벽등반_서울.xls')
r_climb_i = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_암벽등반_인천.xls')

r_iskate_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_인라인_경기도.xls')
r_iskate_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_인라인_서울.xls')
r_iskate_i = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_인라인_인천.xls')

r_hike_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_자전거하이킹_경기도.xls')
r_hike_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_자전거하이킹_서울.xls')
r_hike_i = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_자전거하이킹_인천.xls')

r_casino_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_카지노_서울.xls')

r_cart_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_카트_경기도.xls')

r_track_g = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_트래킹_경기도.xls')
r_track_s = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_트래킹_서울.xls')
r_track_i = pd.read_excel('./data_info/레포츠/레포츠_육상레포츠_트레킹_인천.xls')

r_air_g = pd.read_excel('./data_info/레포츠/레포츠_항공레포츠_경기도.xls')

In [48]:
# 각 데이터 columns 확인

print(so_g.columns)
print(complx_g.columns)
print(water_g.columns)
print(r_atv_g.columns)
print(r_mtb_s.columns)
print(r_ghorse_g.columns)
print(r_jump_g.columns)
print(r_skate_g.columns)
print(r_ski_g.columns)
print(r_shorse_g.columns)
print(r_snowride_g.columns)
print(r_camping_g.columns)
print(r_climb_g.columns)
print(r_iskate_g.columns)
print(r_hike_g.columns)
print(r_casino_s.columns)
print(r_cart_g.columns)
print(r_track_g.columns)
print(r_air_g.columns)

Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')
Index(['명칭', '우편번호', '관리자', '전화번호', '주소', '위도', '경도', '개요', '문의 및 안내', '규모',
       '수용인원', '쉬는날', '개장기간', '이용시간', '입장료', '체험가능연령', '주차시설', '주차요금',
       '유모차 대여 여부', '애완동물 동반 가능 여부', '신용카드 가능 여부', '상세정보'],
      dtype='object')

In [49]:
# '지역' 컬럼 추가 

so_g['지역'] = '경기도'
so_s['지역'] = '서울'

complx_g['지역'] = '경기도'
complx_s['지역'] = '서울'
complx_i['지역'] = '인천'

water_g['지역'] = '경기도'
water_s['지역'] = '서울'
water_i['지역'] = '인천'

r_atv_g['지역'] = '경기도'

r_mtb_s['지역'] = '서울'

r_ghorse_g['지역'] = '경기도'

r_jump_g['지역'] = '경기도'

r_skate_g['지역'] = '경기도'
r_skate_s['지역'] = '서울'
r_skate_i['지역'] = '인천'

r_ski_g['지역'] = '경기도'

r_shorse_g['지역'] = '경기도'
r_shorse_i['지역'] = '인천'

r_snowride_g['지역'] = '경기도'
r_snowride_s['지역'] = '서울'
r_snowride_i['지역'] = '인천'

r_camping_g['지역'] = '경기도'
r_camping_s['지역'] = '서울'
r_camping_i['지역'] = '인천'

r_climb_g['지역'] = '경기도'
r_climb_s['지역'] = '서울'
r_climb_i['지역'] = '인천'

r_iskate_g['지역'] = '경기도'
r_iskate_s['지역'] = '서울'
r_iskate_i['지역'] = '인천'

r_hike_g['지역'] = '경기도'
r_hike_s['지역'] = '서울'
r_hike_i['지역'] = '인천'

r_casino_s['지역'] = '서울'

r_cart_g['지역'] = '경기도'

r_track_g['지역'] = '경기도'
r_track_s['지역'] = '서울'
r_track_i['지역'] = '인천'

r_air_g['지역'] = '경기도'

In [50]:
# 데이터 합치기
reports_df = pd.concat([so_g, so_s, complx_g, complx_s, complx_i, water_g, water_s, water_i, r_atv_g, 
                         r_mtb_s, r_ghorse_g, r_jump_g, r_skate_g, r_skate_s, r_skate_i, r_ski_g, r_shorse_g,
                         r_shorse_i, r_snowride_g, r_snowride_s, r_snowride_i,
                         r_camping_g, r_camping_s, r_camping_i, r_climb_g, r_climb_s, r_climb_i,
                         r_iskate_g, r_iskate_s, r_iskate_i, r_hike_g, r_hike_s, r_hike_i,
                         r_casino_s, r_cart_g, r_track_g, r_track_s, r_track_i, r_air_g])
# 오름차순 정렬
reports_df.sort_values(by='명칭', inplace=True)

In [51]:
# 확인
display(reports_df.head())
display(reports_df.info())

,명칭,우편번호,관리자,전화번호,주소,위도,경도,개요,문의 및 안내,규모,...,입장료,체험가능연령,주차시설,주차요금,유모차 대여 여부,애완동물 동반 가능 여부,신용카드 가능 여부,상세정보,지역,Unnamed: 0
10,24시 마린낚시(전곡항 24 마린낚시),18554.0,NaN,NaN,경기도 화성시 서신면 전곡항로 317,37.189973,126.677301,"경기도 화성시 서신면에 위치해 있는 24시 마린 낚시는 주변에 전곡항, 탄도항, 제...",NaN,NaN,...,NaN,NaN,NaN,NaN,없음,불가,없음,"포인트안내:\n이용요금:선박별 상이 홈페이지 참조\n보유장비: 22인승, 21인승,...",경기도,NaN
1,DMC(디지털미디어시티) 자전거코스,3926.0,디지털미디어시티 홍보관,02-309-7067,서울특별시 마포구 월드컵북로 366,37.577757,126.892151,"DMC(디지털미디어시티) 자전거코스는 DMC 홍보관을 시작으로 상암근린공원 앞, 박...",NaN,NaN,...,NaN,NaN,NaN,NaN,없음,없음,없음,코스안내:[디지털도시와 공원을 넘나들다 - 자전거여행코스]<br />\n소요시간 :...,서울,NaN
474,DMZ 마루캠핑,11004.0,NaN,NaN,경기도 연천군 중면 군중로 399,38.134983,127.019301,경기 최북단에 있는 DMZ 마루캠핑은 경기도 연천군 중면에 위치하고 있다. 부대시설...,NaN,NaN,...,NaN,"<a href=""http://r.camperstory.com/resMain.hbb?...",NaN,주차가능,없음,불가,없음,"이용요금:50,000원 <br>\n※ 이용요금은 변동될 수 있으므로 홈페이지 참조 ...",경기도,NaN
141,GoOut 양주감악산 캠핑장,11401.0,NaN,NaN,경기도 양주시 남면 감악산로 632-32,37.914263,126.956671,GoOut 양주감악산 캠핑장은 경기도 양주시 남면에 위치하고 있다. 기존 양주감악산...,NaN,NaN,...,NaN,NaN,NaN,주차가능,없음,가능,없음,"이용요금:50,000원 <br>\n※ 이용요금은 변동될 수 있으므로 홈페이지 참조 ...",경기도,NaN
47,HJ글램핑2,11110.0,NaN,NaN,경기도 포천시 이동면 금강로 6169,38.078883,127.390194,"인스타 감성 넘치는 포천 럭셔리 글램핑장. 워터슬라이드, 워터 에어바운스 , 수영장...",NaN,NaN,...,NaN,"<a href=""http://site.onda.me/60059/reservation...",NaN,주차가능,없음,불가,없음,"이용요금:69,000원 ~ 219,000원 <br>\n※ 이용요금은 변동될 수 있으...",경기도,NaN

<class 'pandas.core.frame.DataFrame'>
Index: 1081 entries, 10 to 0
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   명칭             1079 non-null   object
 1   우편번호           1044 non-null   float64
 2   관리자            65 non-null     object
 3   전화번호           36 non-null     object
 4   주소             1079 non-null   object
 5   위도             1080 non-null   float64
 6   경도             1080 non-null   float64
 7   개요             1080 non-null   object
 8   문의 및 안내        0 non-null      float64
 9   규모             35 non-null     object
 10  수용인원           31 non-null     object
 11  쉬는날            642 non-null    object
 12  개장기간           583 non-null    object
 13  이용시간           948 non-null    object
 14  입장료            24 non-null     object
 15  체험가능연령         588 non-null    object
 16  주차시설           63 non-null     object
 17  주차요금           894 non-null    object
 18  유모차 대여 여부      916 non-null    object
 19  애완동물 동반 가능 여부  964 non-null    object
 20  신용카드 가능 여부     935 non-null    object
 21  상세정보           1043 non-null   object
 22  지역             1081 non-null   object
 23  Unnamed: 0     1 non-null      object
dtypes: float64(4), object(20)
memory usage: 211.1+ KB

None

In [52]:
# 내보내기
reports_df.to_excel('./data_info/중분류데이터/레포츠.xlsx')